// router/react-cli/src/components/SiteTree/index.js
import React from 'react';
import styles from './SiteTree.module.css';
import SiteTreeNode from '../SiteTreeNode';

export default class SiteTree extends React.Component {
  render() {
    return (
      <section className={styles.siteTree}>
        <SiteTreeNode
          path="/index"
          currentPath={this.props.currentPath}
        />
        <SiteTreeNode
          path="/page-a"
          currentPath={this.props.currentPath}
          child
        />
        <SiteTreeNode
          path="/page-b"
          currentPath={this.props.currentPath}
          lastChild
        />
      </section>
    );
  }
}

// router/vue-cli/src/components/SiteTree.vue
<template>
  <section class="site-tree">
    <SiteTreeNode
      path="/index"
    />
    <SiteTreeNode
      path="/page-a"
      child
    />
    <SiteTreeNode
      path="/page-b"
      last-child
    />
  </section>
</template>

<script>
import SiteTreeNode from './SiteTreeNode';

export default {
  components: {
    SiteTreeNode,
  },
};
</script>

<style scoped>
section.site-tree {
  padding: 20px;
}
</style>
