// router/vue-cli/src/pages/PageA.vue
<template>
  <main class="page-a">
    <PageTitle :title="myName" />
    <hr>
    <SiteTree />
  </main>
</template>

<script>
import PageTitle from '../components/PageTitle';
import SiteTree from '../components/SiteTree';

export default {
  components: {
    PageTitle,
    SiteTree,
  },
  computed: {
    myName() {
      return 'Now at ' + this.$route.path;
    },
  },
};
</script>

<style scoped>
main.page-a {
  background-color: aliceblue;
}
</style>

// router/react-cli/src/pages/PageA/index.js
import React from 'react';
import styles from './PageA.module.css';
import PageTitle from '../../components/PageTitle';
import SiteTree from '../../components/SiteTree';

export default class PageA extends React.Component {
  render() {
    const myName = 'Now at ' + this.props.location.pathname;
    return (
      <main className={styles.pageA}>
        <PageTitle title={myName} />
        <hr />
        <SiteTree currentPath={this.props.location.pathname} />
      </main>
    );
  }
}
