// todo/vue-cli/src/components/TodoList.vue
<template>
  <div class="todo-list-container">
    <ul id="todo-list">
      <todo-list-item
        v-for="(todo, index) in todos"
        :key="index"
        :todo="todo"
        :index="index"
        @done="onDone"/>
    </ul>
  </div>
</template>

<script>
import TodoListItem from './TodoListItem';

export default {
  components: {
    TodoListItem,
  },
  props: {
    todos: {
      type: Array,
      default: () => [],
    },
  },
  methods: {
    onDone(index) {
      this.$emit('remove-todo', index);
    },
  },
};
</script>

<style lang="stylus" scoped>
@import '~@/stylus/variables'

.todo-list-container
  padding: $gap
  width: 100%
</style>

// todo/react-cli/src/components/TodoList/TodoList.js
import React from 'react';
import TodoListItem from '../TodoListItem/TodoListItem';

export default class TodoList extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    const todos = this.props.todos;
    const todoListItems = todos.map((todo, index) => {
      return (
        <TodoListItem
          key={index}
          todo={todo}
          index={index}
          removeTodo={this.props.removeTodo}/>
      );
    });

    return (
      <div className="todo-list-container">
        <ul id="todo-list">
          {todoListItems}
        </ul>
      </div>
    );
  }
}
