// state-management/vue-cli/src/components/Controls.vue
<template>
  <section class="controls">
    <div class="top">
      <button @click="increment">
        INCREMENT
      </button>
      <button @click="decrement">
        DECREMENT
      </button>
    </div>
    <div class="bottom">
      <label>
        <input
          v-model="checked"
          type="checkbox"
        >
        DELAYED ACTION
      </label>
    </div>
  </section>
</template>

<script>
export default {
  data() {
    return {
      checked: false,
    };
  },
  methods: {
    increment() {
      this.checked
        ? this.$store.dispatch('delayedIncrement')
        : this.$store.commit('increment');
    },
    decrement() {
      this.checked
        ? this.$store.dispatch('delayedDecrement')
        : this.$store.commit('decrement');
    },
  },
};
</script>

<style scoped>
section.controls {
  height: 120px;
  background-color: lightseagreen;
  color: black;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

section.controls .top {
  display: flex;
  justify-content: center;
  align-items: center;
  padding-bottom: 20px;
}

section.controls .bottom {
  font-size: 14px;
}

button {
  margin: 0 20px;
}
</style>

// state-management/react-cli/src/components/Controls/index.js
import React, {Component} from 'react';
import styles from './Controls.module.css';
import {connect} from 'react-redux';
import actionCreators from '../../redux/actionCreators';

class Controls extends Component {
  constructor(props) {
    super(props);
    this.state = {checked: false};
    this.handleChange = this.handleChange.bind(this);
    this.handleIncrementButtonClick = this.handleIncrementButtonClick.bind(this);
    this.handleDecrementButtonClick = this.handleDecrementButtonClick.bind(this);
  }
  handleChange(e) {
    this.setState({checked: e.target.value});
  }
  handleIncrementButtonClick(e) {
    this.state.checked
      ? this.props.delayedIncrement()
      : this.props.increment();
  }
  handleDecrementButtonClick(e) {
    this.state.checked
      ? this.props.delayedDecrement()
      : this.props.decrement();
  }
  render() {
    return (
      <section className={styles.controls}>
        <div className={styles.top}>
          <button
            className={styles.button}
            onClick={this.handleIncrementButtonClick}
          >
            INCREMENT
          </button>
          <button
            className={styles.button}
            onClick={this.handleDecrementButtonClick}
          >
            DECREMENT
          </button>
        </div>
        <div className={styles.bottom}>
          <label>
            <input
              value={this.state.checked}
              type="checkbox"
              onChange={this.handleChange}
            />
            DELAYED ACTION
          </label>
        </div>
      </section>
    );
  }
}

export default connect(null, actionCreators)(Controls);
